server:
  port: 9999





#redis配置
spring:
  redis:
    port: 6379
    password:
    host: 127.0.0.1
    jedis:
      pool:
        max-active: 5 #最大连接数
        max-idle: 10 #最大空闲数
        min-idle: 2 #最小空闲数
    timeout: 2000 #连接超时